---
apiVersion: v1
kind: Secret
metadata:
  name: concourse-concourse
  namespace: concourse
  labels:
    app: concourse-concourse
    chart: "concourse-1.15.0"
    release: "concourse"
    heritage: "Tiller"
type: Opaque
data:
  host-key: "${CONCOURSE_HOST_SECRET}"
  host-key-pub: "${CONCOURSE_HOST_PUBLIC}"
  session-signing-key: "${CONCOURSE_SESSION_SECRET}"
  worker-key: "${CONCOURSE_WORKER_SECRET}"
  worker-key-pub: "${CONCOURSE_WORKER_PUBLIC}"
  basic-auth-username: "${CONCOURSE_USERNAME}"
  basic-auth-password: "${CONCOURSE_PASSWORD}"
