---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: concourse-postgresql
  namespace: concourse
  labels:
    app: postgresql
    chart: postgresql-0.13.1
    release: concourse
    heritage: Tiller
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"
