apiVersion: v1
kind: Service
metadata:
  name: concourse-postgresql
  labels:
    app: postgresql
    chart: postgresql-0.13.1
    release: concourse
    heritage: Tiller
spec:
  type: ClusterIP
  ports:
  - name: postgresql
    port: 5432
    targetPort: postgresql
  selector:
    app: postgresql
    release: concourse
