---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: concourse-worker
  namespace: concourse
  labels:
    app: concourse-worker
    chart: "concourse-1.15.0"
    release: "concourse"
    heritage: "Tiller"
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: concourse-worker
