apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: concourse-worker
  labels:
    app: concourse-worker
    chart: concourse-1.15.0
    heritage: Tiller
    release: concourse
