---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: concourse-web
  namespace: concourse
  labels:
    app: concourse-web
    chart: "concourse-1.15.0"
    release: "concourse"
    heritage: "Tiller"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: concourse-web
        release: "concourse"
      annotations:
        {}
        
    spec:
      serviceAccountName: concourse-web
      tolerations:
        []
        
      containers:
        - name: concourse-web
          image: "leeporte/concourse:4.0.0"
          imagePullPolicy: "IfNotPresent"
          args:
            - "web"
            - "--kubernetes-in-cluster"
            - "--add-local-user"
            - $(CONCOURSE_BASIC_AUTH_USERNAME):$(CONCOURSE_BASIC_AUTH_PASSWORD)
            - "--main-team-local-user"
            - $(CONCOURSE_BASIC_AUTH_USERNAME)
            - "--external-url"
            - "http://${EXTERNAL_CONCOURSE_URL}:8080"
          env:
            - name: CONCOURSE_TSA_HOST_KEY
              value: "/concourse-keys/host_key"
            - name: CONCOURSE_SESSION_SIGNING_KEY
              value: "/concourse-keys/session_signing_key"
            - name: CONCOURSE_TSA_AUTHORIZED_KEYS
              value: "/concourse-keys/worker_key.pub"
            - name: POSTGRES_HOST
              value: concourse-postgresql
            - name: POSTGRES_USER
              value: concourse
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: concourse-postgresql
                  key: postgres-password
            - name: POSTGRES_DATABASE
              value: "concourse"
            - name: CONCOURSE_POSTGRES_DATA_SOURCE
              value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST)/$(POSTGRES_DATABASE)?sslmode=disable
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: CONCOURSE_BIND_PORT
              value: "8080"
            - name: CONCOURSE_PEER_URL
              value: "http://$(POD_IP):$(CONCOURSE_BIND_PORT)"
            - name: CONCOURSE_TSA_BIND_PORT
              value: "2222"
            - name: CONCOURSE_ALLOW_SELF_SIGNED_CERTIFICATES
              value: "false"
            - name: CONCOURSE_AUTH_DURATION
              value: "24h"
            - name: CONCOURSE_RESOURCE_CHECKING_INTERVAL
              value: "1m"
            - name: CONCOURSE_OLD_RESOURCE_GRACE_PERIOD
              value: "5m"
            - name: CONCOURSE_RESOURCE_CACHE_CLEANUP_INTERVAL
              value: "30s"
            - name: CONCOURSE_CONTAINER_PLACEMENT_STRATEGY
              value: "random"
            - name: CONCOURSE_BASIC_AUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: concourse-concourse
                  key: basic-auth-username
            - name: CONCOURSE_BASIC_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: concourse-concourse
                  key: basic-auth-password
            - name: CONCOURSE_KUBERNETES_NAMESPACE_PREFIX
              value: concourse-
            - name: CONCOURSE_VAULT_URL
              value: "${VAULT_URL}"
            - name: CONCOURSE_VAULT_AUTH_BACKEND
              value: "cert"
            - name: CONCOURSE_VAULT_CLIENT_KEY
              value: "/concourse-vault-certs/key.pem"
            - name: CONCOURSE_VAULT_CLIENT_CERT
              value: "/concourse-vault-certs/cert.pem"
            - name: CONCOURSE_VAULT_INSECURE_SKIP_VERIFY
              value: "true"

          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - -e
                - |-
                  fly login \
                    -c "http://localhost:8080/" \
                    -k \
                    -u "$CONCOURSE_BASIC_AUTH_USERNAME" \
                    -p "$CONCOURSE_BASIC_AUTH_PASSWORD" \
                    -t "cluster-name-irrelevant"
          ports:
            - name: atc
              containerPort: 8080
            - name: tsa
              containerPort: 2222
          livenessProbe:
            httpGet:
              path: /
              port: atc
            initialDelaySeconds: 120
            timeoutSeconds: 5

          readinessProbe:
            httpGet:
              path: /
              port: atc
            initialDelaySeconds: 5
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            
          volumeMounts:
            - name: concourse-keys
              mountPath: /concourse-keys
              readOnly: true

            - name: concourse-vault-certs
              mountPath: /concourse-vault-certs
              readOnly: true
      affinity:
      volumes:
        - name: concourse-keys
          secret:
            secretName: concourse-concourse
            defaultMode: 0400
            items:
              - key: host-key
                path: host_key
              - key: session-signing-key
                path: session_signing_key
              - key: worker-key-pub
                path: worker_key.pub
        - name: concourse-vault-certs
          secret:
            secretName: concourse-vault-certs
            defaultMode: 0400
            items:
              - key: key-pem
                path: key.pem
              - key: cert-pem
                path: cert.pem
