apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: concourse-web-main
  labels:
    app: concourse-web
    chart: concourse-1.15.0
    heritage: Tiller
    release: concourse
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: concourse-web
  namespace: default
