---
apiVersion: v1
kind: Service
metadata:
  name: concourse-web
  namespace: concourse
  labels:
    app: concourse-web
    chart: "concourse-1.15.0"
    release: "concourse"
    heritage: "Tiller"
    dns: route53
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "${EXTERNAL_CONCOURSE_URL}"
spec:
  type: LoadBalancer
  ports:
    - name: atc
      port: 8080
      targetPort: atc
    - name: tsa
      port: 2222
      targetPort: tsa
  selector:
    app: concourse-web
