---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: concourse-web
  namespace: concourse
  labels:
    app: concourse-web
    chart: concourse-1.15.0
    heritage: Tiller
    release: concourse
