{
 "title": "CPU",
 "panels": [
  {
   "title": "CPU Utilisation",
   "type": "graph",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_cpu_utilisation:avg1m * node:node_num_cpu:sum / scalar(sum(node:node_num_cpu:sum))",
     "legendFormat": "{{node}}",
     "legendLink": "/dashboard/file/k8s-node-rsrc-use.json"
    }
   ]
  },
  {
   "title": "CPU Saturation (Load1)",
   "type": "graph",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_cpu_saturation_load1: / scalar(sum(min(kube_pod_info) by (node)))",
     "legendFormat": "{{node}}",
     "legendLink": "/dashboard/file/k8s-node-rsrc-use.json"
    }
   ]
  }
 ]
}
{
 "title": "Memory",
 "panels": [
  {
   "title": "Memory Utilisation",
   "type": "graph",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_memory_utilisation:ratio",
     "legendFormat": "{{node}}",
     "legendLink": "/dashboard/file/k8s-node-rsrc-use.json"
    }
   ]
  },
  {
   "title": "Memory Saturation (Swap I/O)",
   "type": "graph",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "node:node_memory_swap_io_bytes:sum_rate",
     "legendFormat": "{{node}}",
     "legendLink": "/dashboard/file/k8s-node-rsrc-use.json"
    }
   ]
  }
 ]
}
{
 "title": "Disk",
 "panels": [
  {
   "title": "Disk IO Utilisation",
   "type": "graph",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_disk_utilisation:avg_irate / scalar(:kube_pod_info_node_count:)",
     "legendFormat": "{{node}}",
     "legendLink": "/dashboard/file/k8s-node-rsrc-use.json"
    }
   ]
  },
  {
   "title": "Disk IO Saturation",
   "type": "graph",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_disk_saturation:avg_irate / scalar(:kube_pod_info_node_count:)",
     "legendFormat": "{{node}}",
     "legendLink": "/dashboard/file/k8s-node-rsrc-use.json"
    }
   ]
  }
 ]
}
{
 "title": "Network",
 "panels": [
  {
   "title": "Net Utilisation (Transmitted)",
   "type": "graph",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "node:node_net_utilisation:sum_irate",
     "legendFormat": "{{node}}",
     "legendLink": "/dashboard/file/k8s-node-rsrc-use.json"
    }
   ]
  },
  {
   "title": "Net Saturation (Dropped)",
   "type": "graph",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "node:node_net_saturation:sum_irate",
     "legendFormat": "{{node}}",
     "legendLink": "/dashboard/file/k8s-node-rsrc-use.json"
    }
   ]
  }
 ]
}
{
 "title": "Storage",
 "panels": [
  {
   "title": "Disk Capacity",
   "type": "graph",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(max(node_filesystem_size{fstype=~\"ext[24]\"} - node_filesystem_avail{fstype=~\"ext[24]\"}) by (device,pod,namespace)) by (pod,namespace) / scalar(sum(max(node_filesystem_size{fstype=~\"ext[24]\"}) by (device,pod,namespace))) * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:\n",
     "legendFormat": "{{node}}",
     "legendLink": "/dashboard/file/k8s-node-rsrc-use.json"
    }
   ]
  }
 ]
}
{
 "title": "CPU",
 "panels": [
  {
   "title": "CPU Utilisation",
   "type": "graph",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_cpu_utilisation:avg1m{node=\"$node\"}",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "CPU Saturation (Load1)",
   "type": "graph",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_cpu_saturation_load1:{node=\"$node\"}",
     "legendFormat": "Saturation"
    }
   ]
  }
 ]
}
{
 "title": "Memory",
 "panels": [
  {
   "title": "Memory Utilisation",
   "type": "graph",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_memory_utilisation:{node=\"$node\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Memory Saturation (Swap I/O)",
   "type": "graph",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "node:node_memory_swap_io_bytes:sum_rate{node=\"$node\"}",
     "legendFormat": "Swap IO"
    }
   ]
  }
 ]
}
{
 "title": "Disk",
 "panels": [
  {
   "title": "Disk IO Utilisation",
   "type": "graph",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_disk_utilisation:avg_irate{node=\"$node\"}",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "Disk IO Saturation",
   "type": "graph",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_disk_saturation:avg_irate{node=\"$node\"}",
     "legendFormat": "Saturation"
    }
   ]
  }
 ]
}
{
 "title": "Net",
 "panels": [
  {
   "title": "Net Utilisation (Transmitted)",
   "type": "graph",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "node:node_net_utilisation:sum_irate{node=\"$node\"}",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "Net Saturation (Dropped)",
   "type": "graph",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "node:node_net_saturation:sum_irate{node=\"$node\"}",
     "legendFormat": "Saturation"
    }
   ]
  }
 ]
}
{
 "title": "Disk",
 "panels": [
  {
   "title": "Disk Utilisation",
   "type": "graph",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - sum(max by (device, node) (node_filesystem_avail{fstype=~\"ext[24]\"})) / sum(max by (device, node) (node_filesystem_size{fstype=~\"ext[24]\"}))",
     "legendFormat": "Disk"
    }
   ]
  }
 ]
}
{
 "title": "Headlines",
 "panels": [
  {
   "title": "CPU Requests Commitment",
   "type": "singlestat",
   "format": "percentunit",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores) / sum(node:node_num_cpu:sum)"
    }
   ]
  },
  {
   "title": "CPU Limits Commitment",
   "type": "singlestat",
   "format": "percentunit",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores) / sum(node:node_num_cpu:sum)"
    }
   ]
  },
  {
   "title": "Memory Requests Commitment",
   "type": "singlestat",
   "format": "percentunit",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes) / sum(node_memory_MemTotal)"
    }
   ]
  },
  {
   "title": "Memory Limits Commitment",
   "type": "singlestat",
   "format": "percentunit",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes) / sum(node_memory_MemTotal)"
    }
   ]
  }
 ]
}
{
 "title": "CPU",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total[1m])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}
{
 "title": "CPU Quota",
 "panels": [
  {
   "title": "CPU Quota",
   "type": "table",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total[5m])) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores) by (namespace)"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total[5m])) by (namespace) / sum(kube_pod_container_resource_requests_cpu_cores) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores) by (namespace)"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total[5m])) by (namespace) / sum(kube_pod_container_resource_limits_cpu_cores) by (namespace)"
    }
   ]
  }
 ]
}
{
 "title": "Memory",
 "panels": [
  {
   "title": "Memory Usage (w/o cache)",
   "type": "graph",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}
{
 "title": "Memory Requests",
 "panels": [
  {
   "title": "Requests by Namespace",
   "type": "table",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes) by (namespace)"
    },
    {
     "expr": "sum(container_memory_rss) by (namespace) / sum(kube_pod_container_resource_requests_memory_bytes) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes) by (namespace)"
    },
    {
     "expr": "sum(container_memory_rss) by (namespace) / sum(kube_pod_container_resource_limits_memory_bytes) by (namespace)"
    }
   ]
  }
 ]
}
{
 "title": "CPU Usage",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=\"$namespace\"}[1m])) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  }
 ]
}
{
 "title": "CPU Quota",
 "panels": [
  {
   "title": "CPU Quota",
   "type": "table",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\"}[5m]), \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(label_replace(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\"}[5m]), \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod) / sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(label_replace(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\"}[5m]), \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod) / sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\"}) by (pod)"
    }
   ]
  }
 ]
}
{
 "title": "Memory Usage",
 "panels": [
  {
   "title": "Memory Usage",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  }
 ]
}
{
 "title": "Memory Quota",
 "panels": [
  {
   "title": "Memory Quota",
   "type": "table",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"$namespace\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"$namespace\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod) / sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"$namespace\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\"}) by (pod)"
    }
   ]
  }
 ]
}
{
 "title": "CPU Usage",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=\"$namespace\",pod_name=\"$pod\"}[1m])) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  }
 ]
}
{
 "title": "CPU Quota",
 "panels": [
  {
   "title": "CPU Quota",
   "type": "table",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod_name=\"$pod\"}[5m]), \"container\", \"$1\", \"container_name\", \"(.*)\")) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\", pod=\"$pod\"}) by (container)"
    },
    {
     "expr": "sum(label_replace(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod_name=\"$pod\"}[5m]), \"container\", \"$1\", \"container_name\", \"(.*)\")) by (container) / sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\", pod=\"$pod\"}) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", pod=\"$pod\"}) by (container)"
    },
    {
     "expr": "sum(label_replace(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod_name=\"$pod\"}[5m]), \"container\", \"$1\", \"container_name\", \"(.*)\")) by (container) / sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", pod=\"$pod\"}) by (container)"
    }
   ]
  }
 ]
}
{
 "title": "Memory Usage",
 "panels": [
  {
   "title": "Memory Usage",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\", pod_name=\"$pod\"}) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  }
 ]
}
{
 "title": "Memory Quota",
 "panels": [
  {
   "title": "Memory Quota",
   "type": "table",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"$namespace\", pod_name=\"$pod\"}, \"container\", \"$1\", \"container_name\", \"(.*)\")) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\", pod=\"$pod\"}) by (container)"
    },
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"$namespace\", pod_name=\"$pod\"}, \"container\", \"$1\", \"container_name\", \"(.*)\")) by (container) / sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\", pod=\"$pod\"}) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", pod=\"$pod\"}) by (container)"
    },
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"$namespace\", pod_name=\"$pod\"}, \"container\", \"$1\", \"container_name\", \"(.*)\")) by (container) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", pod=\"$pod\"}) by (container)"
    }
   ]
  }
 ]
}