apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    io.kompose.service: frontend
spec:
  type: NodePort
  ports:
  - name: "80"
    nodePort: 30300
    port: 80
  selector:
    io.kompose.service: frontend
