apiVersion: v1
kind: Service
metadata:
  name: stub-idp-db
  labels:
    io.kompose.service: stub-idp-db
spec:
  type: ClusterIP
  ports:
  - port: 5432
  selector:
    io.kompose.service: stub-idp-db
