apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: stub-idp
  name: stub-idp
spec:
  type: NodePort
  ports:
  - name: "80"
    nodePort: 30140
    port: 80
  selector:
    io.kompose.service: stub-idp
