---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-rp-config
data:
  test-rp.yml: |
    server:
      applicationConnectors:
        - type: http
          port: 80
      adminConnectors:
        - type: http
          port: 50131

      requestLog:
        type: classic
        appenders:
          - type: console
          # - type: file
          #   currentLogFilename: /var/log/debug/test-rp_access.log
          #   archivedLogFilenamePattern: /var/log/debug/test-rp_access.log.%d.gz
          #   archivedFileCount: 7
          # - type: logstash-file
          #   currentLogFilename: /var/log/test-rp_access.log
          #   archivedLogFilenamePattern: /var/log/test-rp_access.log.%d.gz
          #   archivedFileCount: 7
          # - type: logstash-syslog
          #   facility: local2
          #   tag: test-rp

    transactionHost: http://localhost:30130
    dontCacheFreemarkerTemplates: true

    cookieName: test-rp-session

    saml:
      entityId: http://dev-rp.local/SAML2/MD
      expectedDestination: http://localhost

    httpClient:
      timeout: 60s
      timeToLive: 10m
      connectionTimeout: 4s
      # tls:
      #   protocol: TLSv1.2
      #   trustSelfSignedCertificates: true
      #   verifyHostname: false

    allowInsecureMetadataLocation: true

    msaMetadataUri: http://msa/matching-service/SAML2/metadata

    msaEntityId: http://dev-rp-ms.local/SAML2/MD
    hubEntityId: {{ required "samlEngine.metadataEntityID is required" .Values.samlEngine.metadataEntityID }}

    forceAuthentication: false

    serviceInfo:
      name: test-rp

    privateEncryptionKeyConfiguration:
      keyFile: /pki/sample_rp_encryption_primary.pk8

    publicEncryptionCert:
       certFile: /pki/sample_rp_encryption_primary.crt
       name: unusedButCurrentlyRequired

    privateSigningKeyConfiguration:
      keyFile: /pki/sample_rp_signing_primary.pk8

    publicSigningCert:
       certFile: /pki/sample_rp_signing_primary.crt
       name: unusedButCurrentlyRequired

    clientTrustStoreConfiguration:
      # storeUri: /pki/hub.ts
      path: /pki/hub.ts
      password: marshmallow

    logging:
      level: INFO
      appenders:
        - type: console
        # - type: file
        #   currentLogFilename: /var/log/debug/test-rp.log
        #   archivedLogFilenamePattern: /var/log/debug/test-rp.log.%d.gz
        #   archivedFileCount: 7
        #   logFormat: '%-5p [%d{ISO8601,UTC}] %c: %X{logPrefix}%m%n%xEx'
        # - type: logstash-file
        #   currentLogFilename: /var/log/test-rp.log
        #   archivedLogFilenamePattern: /var/log/test-rp.log.%d.gz
        #   archivedFileCount: 7
        # - type: logstash-syslog
        #   facility: local2
        #   tag: test-rp

    javascriptPath: /assets/javascripts
    stylesheetsPath: /assets/stylesheets
    imagesPath: /assets/images

    privateBetaUserAccessRestrictionEnabled: "false"

    tokenServiceUrl:
    tokenServiceUser: 
    tokenServicePassword:

    shouldShowStartWithEidasButton: false
