---
apiVersion: v1
kind: Service
metadata:
  name: external-vault-service
  namespace: vault
  labels:
    app: vault
    vault_cluster: vault-service
spec:
  type: LoadBalancer
  ports:
  - name: vault-client
    port: 80
    protocol: TCP
    targetPort: 8200
  - name: vault-client-ssl
    port: 443
    protocol: TCP
    targetPort: 8200
  - name: prometheus
    port: 9102
    protocol: TCP
    targetPort: 9102
  selector:
    app: vault
    vault_cluster: vault-service
  sessionAffinity: None
