---
apiVersion: "vault.security.coreos.com/v1alpha1"
kind: "VaultService"
metadata:
  name: "vault-service"
  namespace: vault
  labels:
    app: vault-service
spec:
  type: LoadBalancer
  nodes: 2
  version: "0.9.1-0"
  selector:
    app: vault-service
