apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: metadata
  name: metadata
spec:
  ports:
  - port: 80
  selector:
    io.kompose.service: metadata
status:
  loadBalancer: {}
