apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: msa
  name: msa
spec:
  ports:
  - port: 80
  selector:
    io.kompose.service: msa
status:
  loadBalancer: {}
