apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: policy
  name: policy
spec:
  ports:
  - port: 80
  selector:
    io.kompose.service: policy
status:
  loadBalancer: {}
