apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: saml-engine
  name: saml-engine
spec:
  ports:
  - port: 80
  selector:
    io.kompose.service: saml-engine
status:
  loadBalancer: {}
