apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: stub-idp-db
  name: stub-idp-db
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: stub-idp-db
    spec:
      containers:
      - image: postgres
        name: stub-idp-db
        resources: {}
      restartPolicy: Always
status: {}
