apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: stub-idp
  name: stub-idp
spec:
  type: NodePort
  ports:
  - name: "80"
    nodePort: 30140
    port: 80
  selector:
    io.kompose.service: stub-idp
status:
  loadBalancer: {}
