apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: stub-event-sink
  name: stub-event-sink
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: stub-event-sink
    spec:
      containers:
      - env:
        - name: APP_NAME
          value: stub-event-sink
        image: stub-event-sink
        name: stub-event-sink
        resources: {}
      restartPolicy: Always
status: {}
