apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: test-rp
  name: test-rp
spec:
  type: NodePort
  ports:
  - name: "80"
    nodePort: 30130
    port: 80
  selector:
    io.kompose.service: test-rp
status:
  loadBalancer: {}
